Fix implicit-function-declaration errors (#62)
Some functions are called before their prototypes are visible, so gcc's -Wimplicit-function-declaration treat them as compile errors.

Compile error with gcc 14.2.0 (debian 13 version) or gcc 16.1.1
(archlinux version):

```
paste.c: In function 'paste_add':
paste.c:250:17: error: implicit declaration of function 'tmate_send_clipboard_to_host' [-Wimplicit-function-declaration]
  250 |                 tmate_send_clipboard_to_host(pb->data, pb->size);
```

```
server/tmate-daemon-decoder.c: In function 'tmate_sync_layout':
server/tmate-daemon-decoder.c:439:9: error: implicit declaration of function 'pty_pending_flush_stale' [-Wimplicit-function-declaration]
  439 |         pty_pending_flush_stale();

server/tmate-daemon-decoder.c: At top level:
server/tmate-daemon-decoder.c:481:6: warning: conflicting types for 'pty_pending_replay'; have 'void(int)'
  481 | void pty_pending_replay(int pane_id)
```

```
server/tmate-websocket.c: In function 'tmate_disconnect_ws_clients':
server/tmate-websocket.c:1734:9: error: implicit declaration of function 'tmate_send_fin_to_ws_clients' [-Wimplicit-function-declaration]
 1734 |         tmate_send_fin_to_ws_clients(session);
```